services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: cadastro_desenvolvedor_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cadastro_desenvolvedor
    ports:
      - 5432:5432
    volumes:
      - cadastro_desenvolvedor_data:/bitnami/postgresql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cadastro_desenvolvedor_backend
    ports:
      - 3030:3030
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cadastro_desenvolvedor_frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  cadastro_desenvolvedor_data:
